source 'https://rubygems.org'

gem 'rake'

# Component requirements
gem 'activerecord', '>= 3.1', :require => 'active_record'
gem 'bcrypt-ruby', :require => 'bcrypt'
gem 'colorize'
gem 'encrypted_cookie'
gem 'htmlentities'
gem 'httpclient'
gem 'mysql2', '~>0.3.20'
gem 'nokogiri'
gem 'padrino', '0.12.0'
gem 'rmagick'
gem 'sinatra-synchrony'
gem 'slim'
gem 'sqlite3'
gem 'stringex'
gem 'text-hyphen'
gem 'thin'
gem 'translit'
gem 'xml-sitemap'
gem 'whenever'
