source 'https://rubygems.org'

# Distribute your app as a gem
# gemspec

# Server requirements
# gem 'thin' # or mongrel
# gem 'trinidad', :platform => 'jruby'

# Optional JSON codec (faster performance)
# gem 'oj'

# Project requirements
gem 'rake'

# Component requirements
gem 'bcrypt-ruby', :require => 'bcrypt'
gem 'slim'
gem 'activerecord', '>= 3.1', :require => 'active_record'
gem 'sqlite3'
gem 'mysql2'
gem 'colorize'
gem 'nokogiri'
gem 'httpclient'
gem 'imdb'
gem "rmagick", "~>2.13.2", :require => 'RMagick'
gem "youtube_search", ">=0.2.0"
gem "htmlentities"
# Test requirements

# Padrino Stable Gem
#gem 'padrino', '0.11.4'
gem 'padrino', '0.12.0'

# Or Padrino Edge
# gem 'padrino', :github => 'padrino/padrino-framework'

# Or Individual Gems
# %w(core gen helpers cache mailer admin).each do |g|
#   gem 'padrino-' + g, '0.11.4'
# end
